### ISSUE TITLE
Running 2.13.1 -  Multiple Issues

### ISSUE THREAD

**Issue by mrboog12** [wherkamp/Holograms#2]
**Issue 1**
On startup:

```
[17:06:21 WARN]: [Holograms] Task #569 for Holograms v2.13.1 generated an exception
java.lang.NoSuchMethodError: org.bukkit.Material.getMaterial(I)Lorg/bukkit/Material;
        at com.sainttx.holograms.api.line.ItemLine.parseItem(ItemLine.java:60) ~[?:?]
        at com.sainttx.holograms.api.line.ItemLine.<init>(ItemLine.java:30) ~[?:?]
        at com.sainttx.holograms.parser.ItemLineParser.parse(ItemLineParser.java:20) ~[?:?]
        at com.sainttx.holograms.api.HologramPlugin.parseLine(HologramPlugin.java:28) ~[?:?]
        at com.sainttx.holograms.ManagerImpl.load(ManagerImpl.java:68) ~[?:?]
        at com.sainttx.holograms.HologramPlugin.lambda$onEnable$0(HologramPlugin.java:38) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.3.jar:git-Paper-231]
        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.3.jar:git-Paper-231]
        at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1296) ~[patched_1.16.3.jar:git-Paper-231]
        at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:371) ~[patched_1.16.3.jar:git-Paper-231]
        at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1211) ~[patched_1.16.3.jar:git-Paper-231]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999) ~[patched_1.16.3.jar:git-Paper-231]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-231]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]

```
**Issue 2**

when using addline and adding item:[name or ID] then /hologram reload

The Hologram will disappear and will have to manually remove from list and restart server to make work again

```
[17:02:11 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'hologram' in plugin Holograms v2.13.1
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.3.jar:git-Paper-231]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.3.jar:git-Paper-231]
        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.dispatchCommand(CraftServer.java:802) ~[patched_1.16.3.jar:git-Paper-231]
        at net.minecraft.server.v1_16_R2.PlayerConnection.handleCommand(PlayerConnection.java:1918) ~[?:git-Paper-231]
        at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1729) ~[?:git-Paper-231]
        at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.3.jar:git-Paper-231]
        at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.3.jar:git-Paper-231]
        at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.3.jar:git-Paper-231]
        at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[patched_1.16.3.jar:git-Paper-231]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.3.jar:git-Paper-231]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.3.jar:git-Paper-231]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.3.jar:git-Paper-231]
        at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1135) ~[patched_1.16.3.jar:git-Paper-231]
        at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128) ~[patched_1.16.3.jar:git-Paper-231]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.3.jar:git-Paper-231]
        at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:1089) ~[patched_1.16.3.jar:git-Paper-231]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1003) ~[patched_1.16.3.jar:git-Paper-231]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-231]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
Caused by: java.lang.NoSuchMethodError: org.bukkit.Material.getMaterial(I)Lorg/bukkit/Material;
        at com.sainttx.holograms.api.line.ItemLine.parseItem(ItemLine.java:60) ~[?:?]
        at com.sainttx.holograms.api.line.ItemLine.<init>(ItemLine.java:30) ~[?:?]
        at com.sainttx.holograms.parser.ItemLineParser.parse(ItemLineParser.java:20) ~[?:?]
        at com.sainttx.holograms.api.HologramPlugin.parseLine(HologramPlugin.java:28) ~[?:?]
        at com.sainttx.holograms.ManagerImpl.load(ManagerImpl.java:68) ~[?:?]
        at com.sainttx.holograms.ManagerImpl.reload(ManagerImpl.java:41) ~[?:?]
        at com.sainttx.holograms.commands.CommandReload.onCommand(CommandReload.java:19) ~[?:?]
        at com.sainttx.holograms.commands.HologramCommands.onCommand(HologramCommands.java:61) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.3.jar:git-Paper-231]
        ... 18 more

```

**Comment by wherkamp** [comment]
What version of Minecraft version are you running?

**Comment by wherkamp** [comment]
I have an idea what the cause it. When I get off work I will get to fixing it.

**Comment by wherkamp** [comment]
Could you try this build?
https://ci.kingtux.dev/job/Holograms/12/

As a note we do not support the int values of items. You need to use the items name. That can be found here:  https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html

![2020-11-24_20 07 39](https://user-images.githubusercontent.com/11785959/100169147-c0d0a680-2e90-11eb-8250-9474eb0d7a55.png)

**Comment by mrboog12** [comment]
That seems to have fixed the issue

0 startup issues and was able to reload no problem :)

**Comment by wherkamp** [comment]
Awesome!
